version: '3'
services:
  kongdb:
    container_name: kong-db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: kong-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kong-db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - '7000:5432'
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
  kong:
    container_name: kong-be
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: kong-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kong-db
      POSTGRES_PORT: 5432
      APP_PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - kongdb
    volumes:
      - .:/app
      - /app/node_modules
